In [ ]:
import numpy as np

In [ ]:
aarray = np.random.randint(10, 90, (5,5))

In [ ]:
aarray.shape

(5, 5)

In [ ]:
aarray

array([[84, 85, 77, 23, 79],
       [42, 85, 22, 69, 45],
       [55, 65, 50, 83, 84],
       [36, 48, 72, 74, 68],
       [79, 40, 58, 81, 50]])

In [ ]:
aarray[1:4,1:4]

array([[85, 22, 69],
       [65, 50, 83],
       [48, 72, 74]])

In [ ]:
# How to get values larger than 70? 

In [ ]:
# np.where
# Syntax np.where(condition, what_to_do_if_True, what_to_do_if_False)

In [ ]:
np.where(aarray > 70, aarray, 0)

array([[84, 85, 77,  0, 79],
       [ 0, 85,  0,  0,  0],
       [ 0,  0,  0, 83, 84],
       [ 0,  0, 72, 74,  0],
       [79,  0,  0, 81,  0]])

In [ ]:
np.where(aarray > 70, 0, aarray)

array([[ 0,  0,  0, 23,  0],
       [42,  0, 22, 69, 45],
       [55, 65, 50,  0,  0],
       [36, 48,  0,  0, 68],
       [ 0, 40, 58,  0, 50]])

In [ ]:
aarray

array([[84, 85, 77, 23, 79],
       [42, 85, 22, 69, 45],
       [55, 65, 50, 83, 84],
       [36, 48, 72, 74, 68],
       [79, 40, 58, 81, 50]])

In [ ]:
np.where(aarray == 85)

(array([0, 1]), array([1, 1]))

In [ ]:
np.where(aarray == 77)

(array([0]), array([2]))

In [ ]:
## Pandas

In [ ]:
# Installing pandas --> pip install pandas

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'1.1.5'

In [ ]:
# How to read any csv file

In [ ]:
pd.read_csv("adult.data")

39          State-gov   77516  ...  40   United-States   <=50K
0      50   Self-emp-not-inc   83311  ...  13   United-States   <=50K
1      38            Private  215646  ...  40   United-States   <=50K
2      53            Private  234721  ...  40   United-States   <=50K
3      28            Private  338409  ...  40            Cuba   <=50K
4      37            Private  284582  ...  40   United-States   <=50K
...    ..                ...     ...  ...  ..             ...     ...
32555  27            Private  257302  ...  38   United-States   <=50K
32556  40            Private  154374  ...  40   United-States    >50K
32557  58            Private  151910  ...  40   United-States   <=50K
32558  22            Private  201490  ...  20   United-States   <=50K
32559  52       Self-emp-inc  287927  ...  40   United-States    >50K

[32560 rows x 15 columns]

In [ ]:
# If you are running jupyter on Windows 
# /home/user/Download
# /Users/username/Download
# www.google.com/something
# C:\Users\Username\Download
# \t, \r, \n - escape char
"""
pd.read_csv("C:\\Users\\Username\\Downloads\\adult.data")
OR
pd.read_csv("C:/Users/Username/Downloads/adult.data")
OR 
pd.read_csv(r"C:\Users\Username\Downloads\adult.data")
"""

In [ ]:
df = pd.read_csv("adult.data") # df - dataframe

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head() # show us top 5 lines

39          State-gov   77516   Bachelors  ...   0  40   United-States   <=50K
0  50   Self-emp-not-inc   83311   Bachelors  ...   0  13   United-States   <=50K
1  38            Private  215646     HS-grad  ...   0  40   United-States   <=50K
2  53            Private  234721        11th  ...   0  40   United-States   <=50K
3  28            Private  338409   Bachelors  ...   0  40            Cuba   <=50K
4  37            Private  284582     Masters  ...   0  40   United-States   <=50K

[5 rows x 15 columns]

In [ ]:
# when pandas read any file it be default thinks the first row is the HEADER. 

In [ ]:
df = pd.read_csv("adult.data", header=None)
df.head()

0                  1       2           3   ...  11  12              13      14
0  39          State-gov   77516   Bachelors  ...   0  40   United-States   <=50K
1  50   Self-emp-not-inc   83311   Bachelors  ...   0  13   United-States   <=50K
2  38            Private  215646     HS-grad  ...   0  40   United-States   <=50K
3  53            Private  234721        11th  ...   0  40   United-States   <=50K
4  28            Private  338409   Bachelors  ...   0  40            Cuba   <=50K

[5 rows x 15 columns]

In [ ]:
df.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype='int64')

In [ ]:
col_names = ["age", 
 "workclass",
 "fnlwgt", 
 "education", 
 "educationNum",
 "maritalStatus",
 "occupation",
 "relationship",
 "race",
 "sex",
 "capitalGain",
 "capitalLoss",
 "hoursWeekly",
 "nativeCountry", 
 "Above50K"]

In [ ]:
df.head()

0                  1       2           3   ...  11  12              13      14
0  39          State-gov   77516   Bachelors  ...   0  40   United-States   <=50K
1  50   Self-emp-not-inc   83311   Bachelors  ...   0  13   United-States   <=50K
2  38            Private  215646     HS-grad  ...   0  40   United-States   <=50K
3  53            Private  234721        11th  ...   0  40   United-States   <=50K
4  28            Private  338409   Bachelors  ...   0  40            Cuba   <=50K

[5 rows x 15 columns]

In [ ]:
df.columns = col_names

In [ ]:
df.head()

age          workclass  fnlwgt  ... hoursWeekly   nativeCountry Above50K
0   39          State-gov   77516  ...          40   United-States    <=50K
1   50   Self-emp-not-inc   83311  ...          13   United-States    <=50K
2   38            Private  215646  ...          40   United-States    <=50K
3   53            Private  234721  ...          40   United-States    <=50K
4   28            Private  338409  ...          40            Cuba    <=50K

[5 rows x 15 columns]

In [ ]:
df.head(10)

age          workclass  fnlwgt  ... hoursWeekly   nativeCountry Above50K
0   39          State-gov   77516  ...          40   United-States    <=50K
1   50   Self-emp-not-inc   83311  ...          13   United-States    <=50K
2   38            Private  215646  ...          40   United-States    <=50K
3   53            Private  234721  ...          40   United-States    <=50K
4   28            Private  338409  ...          40            Cuba    <=50K
5   37            Private  284582  ...          40   United-States    <=50K
6   49            Private  160187  ...          16         Jamaica    <=50K
7   52   Self-emp-not-inc  209642  ...          45   United-States     >50K
8   31            Private   45781  ...          50   United-States     >50K
9   42            Private  159449  ...          40   United-States     >50K

[10 rows x 15 columns]

In [ ]:
df.tail()

age      workclass  fnlwgt  ... hoursWeekly   nativeCountry Above50K
32556   27        Private  257302  ...          38   United-States    <=50K
32557   40        Private  154374  ...          40   United-States     >50K
32558   58        Private  151910  ...          40   United-States    <=50K
32559   22        Private  201490  ...          20   United-States    <=50K
32560   52   Self-emp-inc  287927  ...          40   United-States     >50K

[5 rows x 15 columns]

In [ ]:
# How many rows and columns are present in data ?? 

In [ ]:
df.shape  # (no_of_rows, no_of_columns)

(32561, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            32561 non-null  int64 
 1   workclass      32561 non-null  object
 2   fnlwgt         32561 non-null  int64 
 3   education      32561 non-null  object
 4   educationNum   32561 non-null  int64 
 5   maritalStatus  32561 non-null  object
 6   occupation     32561 non-null  object
 7   relationship   32561 non-null  object
 8   race           32561 non-null  object
 9   sex            32561 non-null  object
 10  capitalGain    32561 non-null  int64 
 11  capitalLoss    32561 non-null  int64 
 12  hoursWeekly    32561 non-null  int64 
 13  nativeCountry  32561 non-null  object
 14  Above50K       32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [ ]:
# Creat your own dataframe ? 
df2 = pd.DataFrame(columns= ["age", "Name", "Salary"])
df2.head()

Empty DataFrame
Columns: [age, Name, Salary]
Index: []

In [ ]:
# Fill values in columns
df2["Name"] = ["A", "B", "C", "D", "E", np.NaN]
df2["age"]  = [23, 28, 24, 30, None, np.NaN]
df2["Salary"] = [34000, 58000, None, 75000, 50000, np.NaN]

In [ ]:
df2.head(10)

age Name   Salary
0  23.0    A  34000.0
1  28.0    B  58000.0
2  24.0    C      NaN
3  30.0    D  75000.0
4   NaN    E  50000.0
5   NaN  NaN      NaN

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     4 non-null      float64
 1   Name    5 non-null      object 
 2   Salary  4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 272.0+ bytes


In [ ]:
df2.Salary.isna()

0    False
1    False
2     True
3    False
4    False
5     True
Name: Salary, dtype: bool

In [ ]:
df2[df2.Salary.isna()]

age Name  Salary
2  24.0    C     NaN

In [ ]:
df2[df2.age.isna()]

age Name   Salary
4  NaN    E  50000.0

In [ ]:
df2

age Name   Salary
0   23    A  34000.0
1   28    B  58000.0
2   24    C      NaN
3   30    D  75000.0

In [ ]:
df2.age

0    23
1    28
2    24
3    30
Name: age, dtype: int64

In [ ]:
df2["Name"]

0    A
1    B
2    C
3    D
Name: Name, dtype: object

In [ ]:
df2.Salary > 60000

0    False
1    False
2    False
3     True
Name: Salary, dtype: bool

In [ ]:
df2[df2.Salary > 60000]

age Name   Salary
3  30.0    D  75000.0

In [ ]:
df2[df2.Salary > 50000]

age Name   Salary
1  28.0    B  58000.0
3  30.0    D  75000.0

In [ ]:
# Check na /nan for every column ? 
df2.isna()

age   Name  Salary
0  False  False   False
1  False  False   False
2  False  False    True
3  False  False   False
4   True  False   False

In [ ]:
# Return lines if "Salary" column contains NA value 
df2[df2.Salary.isna()]

age Name  Salary
2  24.0    C     NaN
5   NaN  NaN     NaN

In [ ]:
# Return lines if "any" one of the column contains NA value
df2[df2.isna().any(axis=1)]

age Name   Salary
2  24.0    C      NaN
4   NaN    E  50000.0
5   NaN  NaN      NaN

In [ ]:
# Return lines if "all" the columns contain NA value
df2[df2.isna().all(axis=1)]

age Name  Salary
5  NaN  NaN     NaN

In [ ]:
# .loc, .iloc, groupby, merge 