In [ ]:
# Lambda - Is a short way of creating functions. But it can make only less complicated functions 

In [ ]:
# Syntax 
# def function_name(input_1, input_2):
#     Logic_of_function
#     Logic_of_function
#     Logic_of_function
#     Logic_of_function
#     Logic_of_function
#     return output

In [ ]:
def my_sum(a,b):
    return a + b

In [ ]:
my_sum(5, 10)

15

In [ ]:
type(my_sum)

function

In [ ]:
# Syntax 
# lambda input_1, input_2, input_3: return_statement

In [ ]:
my_l = lambda a,b: a+b

In [ ]:
my_l(5, 10)

15

In [ ]:
type(my_l)

function

In [ ]:
calculate_discount = lambda old_discount: old_discount + 3

In [ ]:
calculate_discount(2.3)

5.3

In [ ]:
## List comprehension
alist = [1,2,3,4,5]
# multiply each element of list by 2 
# output - [2,4,6,8,10]

In [ ]:
for item in alist:
    print(item * 2)

2
4
6
8
10


In [ ]:
blist = []
for item in alist: 
    blist.append(item*2)
print(blist)

[2, 4, 6, 8, 10]


In [ ]:
# Syntax 
# [ operation_on_item   for element in your_list]

In [ ]:
# list comprehension 
[item*2 for item in alist]

[2, 4, 6, 8, 10]

In [ ]:
alist = [1,2,3,4,5]
# output = [2,4]

In [ ]:
13/5

2.6

In [ ]:
13%5

3

In [ ]:
# syntax 
# [operation_on_item for item in list if condition]
[item for item in alist if item%2==0]

[2, 4]

In [ ]:
# output [1,3,5]

In [ ]:
[item for item in alist if item%2!=0]

[1, 3, 5]

In [ ]:
[item for item in alist if item%2==1]

[1, 3, 5]

In [ ]:
blist = []
for item in alist: 
    if item%2==1:
        blist.append(item)
print(blist)

In [ ]:
# How to download an external python package 
# ! pip install package_name

In [ ]:
# Upgrade an existing python package 
# ! pip install --upgrade package_name

In [ ]:
# I want to use Numpy
import numpy as np

In [ ]:
# Syntax - 
# import package_name 
# import package_name as small_notation/ alias

In [ ]:
np.__version__

'1.19.5'

### Numpy

In [ ]:
# num + py
# numerical + python


In [ ]:
# array - collection of objects/ elements 
# Array - 1D and matrix - nD 

In [ ]:
#array - [,1,2,3,4,5]
#matrix = [[1,2],
#          [3,4]]

In [ ]:
a_list = [1,2,3,4,5]
a_array = np.array(a_list)

In [ ]:
type(a_list)

list

In [ ]:
type(a_array)

numpy.ndarray

In [ ]:
a_list * 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
a_array * 3

array([ 3,  6,  9, 12, 15])

In [ ]:
a_array.shape

(5,)

In [ ]:
b_array = np.array([[1,  2,  3],
                    [4,  5,  6],
                    [7,  8,  9],
                    [10, 11, 12]])

In [ ]:
type(b_array)

numpy.ndarray

In [ ]:
b_array.shape   # no_of_rows , no_of_columns

(4, 3)

In [ ]:
np.ones(shape=(2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [ ]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros(shape=(3,3), dtype=int) - 4

array([[-4, -4, -4],
       [-4, -4, -4],
       [-4, -4, -4]])

In [ ]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(50, 75, 3)   # start, stop, step

array([50, 53, 56, 59, 62, 65, 68, 71, 74])

In [ ]:
# change the dimention of array
d_array = np.arange(50, 75, 3 )
np.reshape(d_array, (3,3))   # always remember - put your shape in (  ...  )

array([[50, 53, 56],
       [59, 62, 65],
       [68, 71, 74]])

In [ ]:
#reshape d_array in (4,3)
# An array of shape (4,3) should have 12 elements ... 
# d_array has only 9 

In [ ]:
np.random.randint(10, 50, (3, 3))

array([[41, 26, 29],
       [10, 41, 28],
       [10, 32, 12]])

In [ ]:
# Slicing & Indexing 

In [ ]:
e_array = np.random.randint(10, 50, (3, 3))

In [ ]:
e_array

array([[45, 32, 28],
       [35, 34, 44],
       [49, 24, 17]])

In [ ]:
# Golden Rules of Python 
# 1. Everything inside python starts from ZERO

In [ ]:
clist = [11, 15, 19, 18, 13]
clist

[11, 15, 19, 18, 13]

In [ ]:
#  0,  1,  2,  3,  4
# 11, 15, 19, 18, 13

In [ ]:
e_array

array([[45, 32, 28],
       [35, 34, 44],
       [49, 24, 17]])

In [ ]:
# Syntax for indexing 
# array_name[row_number, col_number]
e_array[1,1]

34

In [ ]:
e_array[1, 2]

44

In [ ]:
# Slicing

In [ ]:
clist

[11, 15, 19, 18, 13]

In [ ]:
clist[1:3]  # 1,2

[15, 19]

In [ ]:
# Golden Rule 
# 2. Whenever in range the outer bound is exclusive

In [ ]:
clist[1:4] # 1,2,3

[15, 19, 18]

In [ ]:
e_array

array([[45, 32, 28],
       [35, 34, 44],
       [49, 24, 17]])

In [ ]:
f_array = np.random.randint(10, 50, (5,5))
f_array

array([[32, 18, 46, 43, 44],
       [29, 37, 23, 47, 12],
       [37, 27, 34, 35, 36],
       [30, 39, 14, 34, 16],
       [38, 20, 45, 28, 38]])

In [ ]:
#Syntax 
# array_name[start_row:end_row    ,    start_column:end_column]

In [ ]:
f_array[1:4, 1:3]

array([[37, 23],
       [27, 34],
       [39, 14]])

In [ ]:
f_array[2:4, 2:4]

array([[34, 35],
       [14, 34]])